<?php
/**
 * @file
 * Code for the guq_workbench_moderation feature.
 */

/**
 * Implements hook_views_api().
 */
function guq_workbench_moderation_views_api() {
  return array('api' => 2.0);
}

/**
 * Implements hook_views_default_views().
 */
function guq_workbench_moderation_views_default_views() {
  $module = 'guq_workbench_moderation';
  $directory = 'views';
  $extension = 'view.inc';
  $name = 'view';

  $views = array();
  // Find all the files in the directory with the correct extension.
  $files = file_scan_directory(drupal_get_path('module', $module) . "/$directory", "/.$extension/");
  foreach ($files as $path => $file) {
    require $path;
    if (isset($$name)) {
      $views[$$name->name] = $$name;
    }
  }

  return $views;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function guq_workbench_moderation_ctools_plugin_api($module, $api) {
  // This includes a check for whether Panels is enabled since the Page Manager
  // export is for Panels.
  if ($module == 'page_manager' && $api == 'pages_default' && module_exists('panels')) {
    return array('version' => 1);
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
